### ISSUE TITLE
The problems appeared in colab

### ISSUE THREAD

**Issue by XavierWww** [HLTCHKUST/MulQG#1]
I use colab to run code but appear the following error, how could I solve them?

P1: When use "!conda env create -f multi-qg.yml"  to create conda environment
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement answerability-metric==1.0 (from -r /content/drive/My Drive/MulQG-main/condaenv.i5nwfft4.requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for answerability-metric==1.0 (from -r /content/drive/My Drive/MulQG-main/condaenv.i5nwfft4.requirements.txt (line 1))failed

CondaEnvException: Pip failed

P2: When run "!python process_hotpot.py" 
Traceback (most recent call last):
  File "process_hotpot.py", line 13, in <module>
    from data_util import make_embedding, make_conll_format, make_vocab, convert_idx
ModuleNotFoundError: No module named 'data_utils'

**Comment by Iamfinethanksu** [comment]
We have updated our github https://github.com/HLTCHKUST/MulQG and you can check the newest version of codes and also a more detailed README.

For your specific questions:

A1: The answerability-metric is from https://github.com/PrekshaNema25/Answerability-Metric, you don't need to install it from the conda env yml file, just delete it. (sorry for the trouble), and if you need to measure then follow the instructions on our README or the github page, should be fine.

A2: Yeah, I forgot to upload the data_utils.py file to our git, now it is there, please check.

You can also directly download our checkpoint model and preprocessed data as indicated in the README file.

Thank you~.

**Comment by Iamfinethanksu** [comment]
close

**Comment by XavierWww** [comment]
Thanks for adding more details about your codes, but when I run '!python process_hotpot.py', it appears:

Traceback (most recent call last):
  File "process_hotpot.py", line 243, in <module>
    make_para_dataset()
  File "process_hotpot.py", line 76, in make_para_dataset
    word2idx = make_vocab_from_hotpot(src_word2idx_file, counter, config.vocab_size)
AttributeError: module 'config' has no attribute 'vocab_size''

So, maybe you forget to upload the self-module config.py?

Thank you!
