### ISSUE TITLE
Error 'from GPG.embedding import GloveEmbeddings, BertEmbeddings'

### ISSUE THREAD

**Issue by XavierWww** [HLTCHKUST/MulQG#2]
I use '!bash ./run_train.sh' to train, it appears as follow:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/My Drive/MulQG-main/GPG/main.py", line 2, in <module>
    from GPG.trainer import Trainer
  File "/content/drive/My Drive/MulQG-main/GPG/trainer.py", line 19, in <module>
    from GPG.models.model import GraphPointerGenerator
  File "/content/drive/My Drive/MulQG-main/GPG/models/model.py", line 7, in <module>
    from GPG.models.model_builder import build_glove_embeddings
  File "/content/drive/My Drive/MulQG-main/GPG/models/model_builder.py", line 3, in <module>
    from GPG.embedding import GloveEmbeddings, BertEmbeddings
ModuleNotFoundError: No module named 'GPG.embedding'

Maybe there is no 'embedding.py' in ../MulQG-main/GPG/..

Could you upload it? Thank you!

**Comment by Iamfinethanksu** [comment]
updated :D

**Comment by XavierWww** [comment]
> updated :D

Thank you for uploading embedding.py but I also find that No module named 'GPG.encoders.rnn_encoder'. Could you update again? Thanks~
